In [ ]:
import os 
import pandas as pd
import numpy as np

In [2]:
os.chdir("F:\\Road to Opta\\player_stats\\")
football_dataset = pd.read_csv("football_dataset.csv")

In [3]:
football_dataset = football_dataset.iloc[:,1:]

In [62]:
football_dataset.columns = map(str.lower, football_dataset.columns)

In [63]:
football_dataset.rename(columns={'player name': 'player_name'},inplace=True)

In [64]:
columns = football_dataset.columns.tolist()

In [65]:
new_columns = columns[:1] + columns[-1:] + columns[1:-1]

In [66]:
football_dataset = football_dataset[new_columns]

In [70]:
football_dataset.sort_values(['season', 'league', 'team', 'opp','h/a'], inplace=True)

In [162]:
football_dataset.to_csv("football_dataset_sorted.csv")

In [304]:
test_agg = pd.read_csv("test_agg.csv")

In [305]:
sum_df = test_agg.groupby(['season','league','team','opp','h/a']).agg({'g': 'sum','own':'sum'})

In [306]:
test_agg['team_goals'] = test_agg.groupby(['season','team','league','opp','h/a'])['g'].transform('sum')
test_agg['own_goals'] = test_agg.groupby(['season','team','league','opp','h/a'])['own'].transform('sum')

In [307]:
test_agg_2 = test_agg[['season','team','league','opp','h/a','team_goals','own_goals']]

In [308]:
test_agg_2 = test_agg_2.drop_duplicates().reset_index(drop=True)

In [309]:
for index, row in test_agg.iterrows():
    for i, r in test_agg_2.iterrows():
        if ((row[1] == r[0]) & (row[2]==r[3]) & \
                                      (row[3] == r[2]) & (row[4]==r[1]) & \
                                        (row[5] != r[4])):
#             print("index", index, "team_goals", row[-2], "opp goals", r[5], "own_goals", r[6])
            test_agg.loc[index,"opp_goals"] = r[5]
    
            #test_agg.loc[index,"own_goals"] = row[53]
            if r[6]>0:
                test_agg.loc[index,'team_goals'] = test_agg.loc[index,'team_goals'] + r[6]
test_agg["opp_goals"] = test_agg["opp_goals"] + test_agg["own_goals"]

In [311]:
test_agg.to_csv("test_agg_opp_goals.csv")

In [167]:
test_agg

,player_name,season,team,league,opp,h/a,form,pos,gp,min,...,ecl,punch,alb,atb,lmt,toff,bcm,bcs,attdr,team_goals
0,Jeremy Mathieu,2016-2017,BAR,LIGA,ALA,A,433,DC,1,90,...,4,0,5,0,0,0,0,0,0,5
1,Lucas Digne,2016-2017,BAR,LIGA,ALA,A,433,DL,1,90,...,3,0,2,0,0,1,0,0,7,5
2,Samuel Umtiti,2016-2017,BAR,LIGA,ALA,A,433,DC,1,66,...,1,0,5,0,0,0,0,0,0,5
3,Jordi Alba,2016-2017,BAR,LIGA,ALA,A,433,SUB,1,24,...,0,0,0,0,0,0,0,0,1,5
4,Sergi Roberto,2016-2017,BAR,LIGA,ALA,A,433,SUB,1,18,...,1,0,0,0,0,0,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Manu Garcia,2016-2017,ALA,LIGA,BAR,H,442,SUB,0,0,...,0,0,0,0,0,0,0,0,0,0
68,Victor Camarasa,2016-2017,ALA,LIGA,BAR,H,442,SUB,0,0,...,0,0,0,0,0,0,0,0,0,0
69,Ruben Sobrino,2016-2017,ALA,LIGA,BAR,H,442,ML,1,90,...,1,0,0,0,0,0,0,0,3,0
70,Christian Santos,2016-2017,ALA,LIGA,BAR,H,442,FW,1,90,...,3,0,1,0,0,2,1,0,2,0
71,Deyverson,2016-2017,ALA,LIGA,BAR,H,442,SUB,0,0,...,0,0,0,0,0,0,0,0,0,0

In [50]:
for index, row in test_agg.iterrows():
    print(row[1],row[2],row[3],row[4], row[5], row[-2])

2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BAY BUND BMG H 2
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0
2016-2017 BMG BUND BAY H 0

In [42]:
for i, r in test_agg_2.iterrows():
    print(r[0],r[1],r[2],r[3], r[4], r[5])

2016-2017 BAY BUND BMG A 1
2016-2017 BAY BUND BMG H 2
2016-2017 BMG BUND BAY A 0
2016-2017 BMG BUND BAY H 0

In [59]:
for index, row in test_agg.iterrows():
    for i, r in test_agg_2.iterrows():
        test_agg['opp_goals'] = np.where((row[1] == r[0]) & (row[2]==r[3]) & \
                                      (row[3] == r[2]) & (row[4]==r[1]) & \
                                        (row[5] != r[4]), "",r[5])

In [60]:
test_agg

,player_name,season,team,league,opp,h/a,form,pos,gp,min,...,punch,alb,atb,lmt,toff,bcm,bcs,attdr,team_goals,opp_goals
0,Philipp Lahm,2016-2017,BAY,BUND,BMG,A,4231,DR,1,90,...,0,2,0,0,0,0,0,1,1,0
1,David Alaba,2016-2017,BAY,BUND,BMG,A,4231,DL,1,90,...,0,1,0,0,2,0,0,0,1,0
2,Mats Hummels,2016-2017,BAY,BUND,BMG,A,4231,DC,1,90,...,0,3,0,0,0,0,0,0,1,0
3,Joshua Kimmich,2016-2017,BAY,BUND,BMG,A,4231,SUB,1,13,...,0,0,0,0,0,0,0,1,1,0
4,Rafinha,2016-2017,BAY,BUND,BMG,A,4231,SUB,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Thorgan Hazard,2016-2017,BMG,BUND,BAY,H,442,SUB,1,26,...,0,1,0,0,0,0,0,1,0,0
68,Laszlo Benes,2016-2017,BMG,BUND,BAY,H,442,SUB,1,9,...,0,0,0,0,0,0,0,0,0,0
69,Nico Schulz,2016-2017,BMG,BUND,BAY,H,442,SUB,0,0,...,0,0,0,0,0,0,0,0,0,0
70,Raffael,2016-2017,BMG,BUND,BAY,H,442,FW,1,90,...,0,2,0,0,0,0,0,5,0,0
71,Josip Drmic,2016-2017,BMG,BUND,BAY,H,442,SUB,1,17,...,0,0,0,0,0,0,0,0,0,0

In [118]:
for index, row in test_agg.iterrows():
    for i, r in test_agg_2.iterrows():
        print(row[1],r[0],row[2],r[3], row[3],r[2],row[4],r[1],row[5],r[4],r[5])

2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR A H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA A H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H A 5
2016-2017 2016-2017 BAR ALA LIGA LIGA ALA BAR H H 1
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H A 2
2016-2017 2016-2017 BAR BAR LIGA LIGA ALA ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5

2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR A H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA A H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H A 5
2016-2017 2016-2017 ALA ALA LIGA LIGA BAR BAR H H 1
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H A 2
2016-2017 2016-2017 ALA BAR LIGA LIGA BAR ALA H H 0

In [61]:
os.chdir("F:\\Road to Opta\\player_stats\\")
test_agg.to_csv("test_agg_both_teams.csv")

In [ ]:
# test_agg.loc[(test_agg['team'] == test_agg_2['opp']) & (test_agg['opp'] == test_agg_2['team']) \
#              & (test_agg['league'] == test_agg_2['league']) & \
#              (test_agg['season'] == test_agg_2['season']) & (test_agg['h/a'] != test_agg_2['h/a']), \
#              'opp_goals'] = test_agg_2['team_goals']